log:
  level: error
  file: "/tmp/mosdns.log"

include: []

data_providers:
  - tag: geoip
    file: "/usr/share/v2ray/geoip.dat"
    auto_reload: true

  - tag: geosite
    file: "/usr/share/v2ray/geosite.dat"
    auto_reload: true

  - tag: whitelist
    file: "/etc/mosdns/rule/whitelist.txt"
    auto_reload: true

  - tag: blocklist
    file: "/etc/mosdns/rule/blocklist.txt"
    auto_reload: true

  - tag: pihole
    file: "/etc/mosdns/rule/pi-hole.txt"
    auto_reload: true

  - tag: hosts
    file: "/etc/mosdns/rule/hosts.txt"
    auto_reload: true

  - tag: redirect
    file: "/etc/mosdns/rule/redirect.txt"
    auto_reload: true

plugins:

 ################ DNS #################
  - tag: ali
    type: fast_forward
    args:
      upstream:
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.5.5.5"
          trusted: true
          enable_http3: true
        - addr: "tls://dns.alidns.com"
          dial_addr: "223.6.6.6"
          trusted: true
        - addr: udpme://223.5.5.5

  - tag: dnspod
    type: fast_forward
    args:
      upstream:
        - addr: "https://1.12.12.12/dns-query"
          trusted: true
          enable_http3: true
        - addr: "tls://120.53.53.53"
          trusted: true
        - addr: udpme://119.29.29.29

  - tag: google
    type: "fast_forward"
    args:
      upstream:
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8"
          trusted: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.4.4"
          trusted: true
        - addr: "tls://dns.google"
          dial_addr: "8.8.4.4"
          trusted: true
          enable_pipeline: true
        - addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          trusted: true
        - addr: "udpme://8.8.8.8"
        - addr: "udpme://8.8.4.4"

  - tag: cloudflare
    type: "fast_forward"
    args:
      upstream:
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.0.0.1"
          trusted: true
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.1.1.1"
          trusted: true
        - addr: "udpme://1.0.0.1"
        - addr: "udpme://1.1.1.1"

  - tag: ips_ipv6
    type: "fast_forward"
    args:
      upstream:
        - addr: "240e:1f:1::1"
        - addr: "240e:1f:1::33"
        - addr: "2409:8057:2000:6::8"
        - addr: "2409:8057:2000:0::8"
        - addr: "2408:8888::8"
        - addr: "2408:8899::8"
        - addr: "udpme://2400:3200::1"
        - addr: "udpme://2400:3200:baba::1"
        - addr: "udpme://2402:4e00::"
        - addr: "udpme://2400:da00::6666"
        - addr: "udpme://240e:4c:4008::1"
        - addr: "udpme://240e:4c:4808::1"
        - addr: "udpme://240C::6666"
        - addr: "udpme://2001:dc7:1000::1"

  - tag: oversea_ipv6
    type: fast_forward
    args:
      upstream:
        - addr: "udpme://2001:4860:4860::8888"
        - addr: "udpme://2001:4860:4860::8844"
        - addr: "udpme://2606:4700:4700::1111"
        - addr: "udpme://2620:0:ccc::2"
        - addr: "udpme://2620:119:35::35"
        - addr: "udpme://2606:4700:4700::1111"
        - addr: "udpme://2606:4700:4700::1001"

  - tag: other_dns
    type: "fast_forward"
    args:
      upstream:
        - addr: udpme://1.12.13.53
        - addr: udpme://180.76.76.76
        - addr: udpme://52.80.52.52
        - addr: udpme://114.114.114.114

  - tag: ips_dns
    type: "fast_forward"
    args:
      upstream:
        - addr: 202.96.134.133
        - addr: 202.96.128.166

  - tag: query_is_whitelist_domain
    type: query_matcher
    args:
      domain:
        - "provider:whitelist"

  - tag: query_is_blocklist_domain
    type: query_matcher
    args:
      domain:
        - "provider:blocklist"

  - tag: query_is_hosts_domain
    type: hosts
    args:
      hosts:
        - "provider:hosts"

  - tag: query_is_redirect_domain
    type: redirect
    args:
      rule:
        - "provider:redirect"

  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:geosite:cn,apple-cn,icloud,google-cn,tld-cn,geolocation-cn,category-games@cn"

  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:geosite:gfw,disney,greatfire,geolocation-!cn"

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - "provider:geoip:cn"

  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - "provider:geosite:category-ads-all,category-ads"

  - tag: query_is_pi_hole
    type: query_matcher
    args:
      domain:
        - "provider:pihole"

  - tag: match_qtype65
    type: query_matcher
    args:
      qtype: [65]


  ################ 序列 #################

  # local 序列
  - tag: forward_local
    type: sequence
    args:
      exec:
        - parallel:
            - - ips_ipv6
            - - ips_dns
            - - ali
            - - dnspod
            - - other_dns

  # remote 序列
  - tag: forward_remote
    type: sequence
    args:
      exec:
        - parallel:
            - - oversea_ipv6
            - - google
            - - cloudflare

  - tag: "main_sequence"
    type: "sequence"
    args:
      exec:
        - query_is_hosts_domain
        - query_is_redirect_domain

        - if: query_is_whitelist_domain
          exec:
            - forward_local
            - _return

        - if: "query_is_blocklist_domain || query_is_ad_domain  || query_is_pi_hole || match_qtype65"
          exec:
            - _new_nxdomain_response
            - _return

        - if: query_is_local_domain
          exec:
            - forward_local
            - if: "response_has_local_ip"
              exec:
                - _return

        - if: query_is_non_local_domain
          exec:
            - _prefer_ipv4
            - forward_remote # 无污染
            - if: "!response_has_local_ip" # 结果是 非cnip
              exec:
                - _return # 结束

        - primary:
            - forward_local
            - if: "(! response_has_local_ip) && [_response_valid_answer]"
              exec:
                - _drop_response
          secondary:
            - forward_remote
          fast_fallback: 120

  - tag: my_sequence
    type: sequence
    args:
      exec:
        - _misc_optm
        - main_sequence

servers:
  - exec: my_sequence
    listeners:
      - protocol: udp
        addr: ":5335"
      - protocol: tcp
        addr: ":5335"
api:
    http: "0.0.0.0:8080"