#!/bin/sh

/etc/uci-defaults/luci-passwall

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

ln -sf /sbin/ip /usr/bin/ip

sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i 's/root::0:0:99999:7:::/root:$1$pl544Ip9$eVk3sgSxTPNYWwV5cI4wU.:19326:0:99999:7:::/g' /etc/shadow


sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R22.11.11'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

mv /usr/share/xray/geoip.dat /usr/share/v2ray/geoip.dat 
mv /usr/share/xray/geosite.dat /usr/share/v2ray/geosite.dat 
rm -rf /usr/share/xray

uci set network.lan.ipaddr='192.168.0.1'   # 默认 IP 地址
uci set network.lan.proto='static'   # 静态 IP
uci set network.lan.type='bridge'   # 接口类型：桥接
uci set network.lan.ifname='eth1'   # 网络端口：默认 eth0，第一个接口
uci set network.lan.netmask='255.255.255.0' # 子网掩码
uci set network.lan.gateway='192.168.0.1'   # 默认网关地址（主路由 IP）
uci set network.lan.dns='192.168.0.1'  # 默认上游 DNS 地址
uci commit network

uci set dhcp.@dnsmasq[0].dnsforwardmax='10000'
uci set dhcp.@dnsmasq[0].cachesize='0'
uci set dhcp.@dnsmasq[0].mini_ttl='0'
uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci set dhcp.@dnsmasq[0].noresolv='1'
uci set dhcp.@dnsmasq[0].nohosts='1'
uci set dhcp.@dnsmasq[0].nonegcache='1'
uci set dhcp.@dnsmasq[0].boguspriv='0'
uci set dhcp.@dnsmasq[0].domain='c2201.home'
uci set dhcp.@dnsmasq[0].server='127.0.0.1#5334'
uci set dhcp.@dnsmasq[0].filter_aaaa='0'
uci set dhcp.lan.start='50'
uci set dhcp.lan.limit='150'
uci commit dhcp

echo 'server=127.0.0.1#5334' >> /etc/dnsmasq.conf

uci set mosdns.config.enabled='1'
uci set mosdns.config.configfile='/etc/mosdns/config_custom.yaml'
uci set mosdns.config.redirect='0'
uci commit mosdns

uci set network.wan.proto='pppoe'
uci set network.wan.username='pppoe-wan-username'
uci set network.wan.password='pppoe-wan-password'
uci set network.wan.mtu='1492'
uci set network.globals.ula_prefix=''
uci set network.wan.peerdns='0'
uci set network.wan6.peerdns='0'
uci commit network

uci set sqm.eth1.enabled='1'
uci set sqm.eth1.download='856625'
uci set sqm.eth1.upload='48000'
uci set sqm.eth1.interface='eth0'
uci commit sqm

uci set uuplugin.uuplugin.enabled='1'
uci commit uuplugin

uci set unbound.ub_main.enabled='1'
uci set unbound.ub_main.manual_conf='1'
uci set unbound.ub_main.extended_luci='1'
uci set unbound.ub_main.listen_port='5334'
uci commit unbound

uci delete passwall.AD
uci delete passwall.Direct
uci delete passwall.Netflix
uci delete passwall.Proxy
uci commit passwall;

uci set passwall.BT=shunt_rules
uci set passwall.BT.remarks='BT'
uci set passwall.BT.protocol='bittorrent'
uci set passwall.Speed=shunt_rules
uci set passwall.Speed.remarks='Speed'
uci set passwall.Speed.domain_list='speed.c2201.rule'
uci set passwall.Netflix=shunt_rules
uci set passwall.Netflix.remarks='Netflix'
uci set passwall.Netflix.domain_list='fast.com
netflix
netflix.com
netflix.net
nflxso.net
nflxext.com
nflximg.com
nflximg.net
nflxvideo.net
netflixdnstest0.com
netflixdnstest1.com
netflixdnstest2.com
netflixdnstest3.com
netflixdnstest4.com
netflixdnstest5.com
netflixdnstest6.com
netflixdnstest7.com
netflixdnstest8.com
netflixdnstest9.com
geosite:netflix
geosite:disney
geosite:youtube
geosite:twitter'
uci set passwall.Direct=shunt_rules
uci set passwall.Direct.remarks='Direct'
uci set passwall.Direct.domain_list='geosite:cn
geosite:apple-cn
geosite:icloud
geosite:google-cn
geosite:geolocation-cn
geosite:private
geosite:tld-cn
geosite:category-games@cn
home.caijinbiao.cn
home6.caijinbiao.cn
c2201.top
store.c2201.top
speed.c2201.top
www.linksys.com
linksys.com
bing.com.cn
cn.bing.com
cn.bing.net
xboxlive.cn
ookla.com
ooklaserver.net
pingtest.net
speedtest.co
speedtest.net
speedtestcustom.com
webtest.net
assets1.xboxlive.com
assets2.xboxlive.com
dlassets.xboxlive.com
dlassets2.xboxlive.com
d1.xboxlive.com
d1.xboxlive.com
d2.xboxlive.com
xvcf1.xboxlive.com
xvcf2.xboxlive.com
test-ipv6.com
ooklaserver.net'
uci set passwall.Direct.ip_list='223.5.5.5/32
119.29.29.29/32
180.76.76.76/32
114.114.114.114/32
geoip:cn
geoip:private'
uci set passwall.Proxy=shunt_rules
uci set passwall.Proxy.remarks='Proxy'
uci set passwall.Proxy.domain_list='geosite:gfw
geosite:greatfire
geosite:geolocation-!cn'
uci set passwall.Proxy.ip_list='149.154.160.0/20
91.108.4.0/22
91.108.56.0/24
109.239.140.0/24
67.198.55.0/24
8.8.4.4
8.8.8.8
208.67.222.222
208.67.220.220
1.1.1.1
1.1.1.2
1.0.0.1
9.9.9.9
149.112.112.112
2001:67c:4e8::/48
2001:b28:f23c::/48
2001:b28:f23d::/48
2001:b28:f23f::/48
2001:b28:f242::/48
2001:4860:4860::8888
2001:4860:4860::8844
2606:4700:4700::1111
2606:4700:4700::1001'
uci set passwall.@global[0].enabled='1'
uci set passwall.@global[0].tcp_node='myshunt'
uci set passwall.@global[0].udp_node='tcp'
uci set passwall.@global[0].dns_mode='udp'
uci set passwall.@global[0].remote_dns='127.0.0.1:5334'
uci set passwall.@global_forwarding[0].tcp_proxy_way='tproxy'
uci set passwall.@global_forwarding[0].ipv6_tproxy='1'
uci set passwall.@global_rules[0].geosite_update='1'
uci set passwall.@global_rules[0].geoip_update='1'
uci set passwall.@global_rules[0].auto_update='1'
uci set passwall.@global_rules[0].week_update='5'
uci set passwall.@global_rules[0].time_update='4'
uci set passwall.myshunt=nodes
uci set passwall.myshunt.remarks='分流总节点'
uci set passwall.myshunt.type='Xray'
uci set passwall.myshunt.protocol='_shunt'
uci set passwall.myshunt.BT='_direct'
uci set passwall.myshunt.Direct='_direct'
uci set passwall.myshunt.domainStrategy='IPOnDemand'
uci set passwall.myshunt.Speed='65877591bdc242a7a61b325518c66802'
uci set passwall.myshunt.Netflix='f58512f7cb784412a7ad5f7679022cc7'
uci set passwall.myshunt.Proxy='e4ca1bb7fe784219a91093a27ce3d90b'
uci set passwall.myshunt.default_node='_direct'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b=nodes
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.remarks='c2201.top'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.type='Xray'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.protocol='trojan'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.address='c2201.top'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.port='443'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.password='c2201.top-password'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.tls='1'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.xtls='0'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.alpn='h2'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.tls_serverName='c2201.top'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.fingerprint='disable'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.transport='grpc'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.grpc_serviceName='c2201.top-service-name'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.grpc_mode='gun'
uci set passwall.e4ca1bb7fe784219a91093a27ce3d90b.grpc_initial_windows_size='0'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7=nodes
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.tls='1'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.protocol='trojan'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.grpc_initial_windows_size='0'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.port='443'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.alpn='h2'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.fingerprint='disable'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.grpc_mode='gun'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.type='Xray'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.xtls='0'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.transport='grpc'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.add_mode='1'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.remarks='store.c2201.top'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.address='store.c2201.top'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.password='store.c2201.top-password'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.tls_serverName='store.c2201.top'
uci set passwall.f58512f7cb784412a7ad5f7679022cc7.grpc_serviceName='store.c2201.top-service-name'
uci set passwall.65877591bdc242a7a61b325518c66802=nodes
uci set passwall.65877591bdc242a7a61b325518c66802.tls='1'
uci set passwall.65877591bdc242a7a61b325518c66802.protocol='trojan'
uci set passwall.65877591bdc242a7a61b325518c66802.grpc_initial_windows_size='0'
uci set passwall.65877591bdc242a7a61b325518c66802.port='443'
uci set passwall.65877591bdc242a7a61b325518c66802.alpn='h2'
uci set passwall.65877591bdc242a7a61b325518c66802.fingerprint='disable'
uci set passwall.65877591bdc242a7a61b325518c66802.type='Xray'
uci set passwall.65877591bdc242a7a61b325518c66802.grpc_mode='gun'
uci set passwall.65877591bdc242a7a61b325518c66802.add_mode='1'
uci set passwall.65877591bdc242a7a61b325518c66802.xtls='0'
uci set passwall.65877591bdc242a7a61b325518c66802.transport='grpc'
uci set passwall.65877591bdc242a7a61b325518c66802.remarks='speed.c2201.top'
uci set passwall.65877591bdc242a7a61b325518c66802.address='speed.c2201.top'
uci set passwall.65877591bdc242a7a61b325518c66802.password='speed.c2201.top-password'
uci set passwall.65877591bdc242a7a61b325518c66802.tls_serverName='speed.c2201.top'
uci set passwall.65877591bdc242a7a61b325518c66802.grpc_serviceName='speed.c2201.top-service-name'

uci commit passwall;

exit 0
